name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
        
    - name: Verify formatting
      run: |
        echo "Checking formatting..."
        if ! deno fmt --check; then
          echo "❌ Formatting errors found. Please run 'deno fmt' locally and commit the changes."
          exit 1
        fi
        echo "✅ Formatting check passed."
      
    - name: Run linter
      run: deno lint
      
    - name: Run type check
      run: deno check main.ts
      
    - name: Run tests
      run: deno test --allow-all